"""empty message

Revision ID: d30420f21787
Revises: 
Create Date: 2023-09-15 18:37:03.688298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30420f21787'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_email'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('provider_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('RIF', sa.Integer(), nullable=False),
    sa.Column('company_industry', sa.String(length=200), nullable=False),
    sa.Column('company_description', sa.String(length=200), nullable=False),
    sa.Column('presupuesto_minimo_de_usuario', sa.Integer(), nullable=False),
    sa.Column('clients_amount_per_month_question', sa.Boolean(), nullable=False),
    sa.Column('clients_amount_per_month_description', sa.Integer(), nullable=True),
    sa.Column('clients_amount_per_wedding_question', sa.Boolean(), nullable=False),
    sa.Column('clients_amount_per_wedding_description', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_novio', sa.String(length=200), nullable=False),
    sa.Column('name_novia', sa.String(length=200), nullable=False),
    sa.Column('wedding_date', sa.Date(), nullable=False),
    sa.Column('wedding_time', sa.String(length=10), nullable=False),
    sa.Column('presupuesto_estimado', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(length=500), nullable=False),
    sa.Column('guests_average', sa.Integer(), nullable=False),
    sa.Column('food_question', sa.Boolean(), nullable=False),
    sa.Column('music_question', sa.Boolean(), nullable=False),
    sa.Column('visual_media_question', sa.Boolean(), nullable=False),
    sa.Column('legal_documentation_question', sa.Boolean(), nullable=False),
    sa.Column('cloth_question', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(length=10), nullable=False),
    sa.Column('provider_sheet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_sheet_id'], ['provider_sheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(length=10), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_membership')
    op.drop_table('provider_membership')
    op.drop_table('wedding')
    op.drop_table('provider_sheet')
    op.drop_table('user')
    op.drop_table('provider')
    # ### end Alembic commands ###
